apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - uns-acr-secret.yaml
  - litmusautomation-uns-centralportal-pull-secret.yaml
  - litmus-uns-values-configmap.yaml
  - helmrepository.yaml
  - helmrelease.yaml

namespace: kkm
