apiVersion: v1
kind: ConfigMap
metadata:
  name: litmus-uns-values
  namespace: uns
data:
  values.yaml: |
    images:
      keycloak:
        name: "litmus.azurecr.io/keycloak"
        tag: "1.2.9"
        pullPolicy: IfNotPresent
      mqtt:
        name: "litmus.azurecr.io/mqtt"
        tag: "1.2.9"
        pullPolicy: IfNotPresent
      webui:
        name: "litmus.azurecr.io/webui"
        tag: "1.2.9"
        pullPolicy: IfNotPresent
      postgres:
        name: "litmus.azurecr.io/postgres"
        tag: "16.1"
        pullPolicy: IfNotPresent
      redis:
        name: "litmus.azurecr.io/redis"
        tag: "7.2.4-alpine3.19"
        pullPolicy: IfNotPresent
      haproxy:
        name: "litmus.azurecr.io/haproxy"
        tag: "2.8.9"
        pullPolicy: IfNotPresent
      curl:
        name: "litmus.azurecr.io/curl"
        tag: "8.7.1"
        pullPolicy: IfNotPresent

    # Correct imagePullSecrets as a list (empty if no secret)
    imagePullSecrets:
      - name: uns-acr-secret  # Replace with the actual secret name, if necessary.
    
    nameOverride: ""
    fullnameOverride: ""
    
    serviceAccount:
      create: true
      automount: true
      annotations: {}
      name: ""
    
    ingress:
      enabled: false
      annotations: {}
      host: uns.local
      tls:
        secretName: "luns-default-tls"
    
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"  # Azure-specific ILB annotation
      ports:
        http: 80
        https: 443
        mqtt: 1883
        mqtts: 8883
        mqttWs: 1882
        mqttsWs: 8882
    
    resources: {}
    
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    
    nodeSelector: {}
    
    tolerations: []
    
    affinity: {}
    
    luns:
      createTlsSecret: true
      tlsSecretName: "luns-default-tls"
      tls:
        ttl: 390
        altNames:
          - "uns.local"
        ipList:
          - "127.0.0.1"
    
    postgres:
      enabled: true
      storage:
        size: "10Gi"
      annotations: {}
      external:
        enabled: false
        host: "postgres.local"
        port: 5432
        secretName: ext-db-creds
    
    redis:
      storage:
        size: "10Gi"
      labels: {}
    
    mqtt:
      replicaCount: 3
      redisTopicsTTL: "24h"
      logLevel: "info"
    
    keycloak:
      realm: "standalone"
      resources:
        requests:
          cpu: "0.05"
          memory: "600Mi"
          ephemeral-storage: "100Mi"
        limits:
          cpu: "1"
          memory: "700Mi"
        ephemeral-storage: "500Mi"
    
    haproxy:
      replicaCount: 2
      mqttDefaultBackendCount: 10
    
    webui:
      labels: {}
      annotations: {}
