# ClusterRole to grant permissions to manage PersistentVolumes
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Name of the role
  name: flux-applier-pv-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

---

# ClusterRoleBinding to bind the service account to the ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-applier-pv-role-binding
subjects:
  - kind: ServiceAccount
    name: flux-applier  # This is the service account used by Flux
    namespace: postgresql  # Ensure this matches the namespace of the service account
roleRef:
  kind: ClusterRole
  name: flux-applier-pv-role  # Refers to the ClusterRole we just created
  apiGroup: rbac.authorization.k8s.io
