---
# Secret for PostgreSQL credentials (username, password, and database)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret-2  # Updated secret name
  namespace: kkm
  labels:
    app: postgres-2  # Updated label to match the second deployment
type: Opaque
data:
  POSTGRES_DB: cHNfZGI=  # Base64-encoded value of 'ps_db'
  POSTGRES_USER: YWRtaW4=  # Base64-encoded value of 'admin'
  POSTGRES_PASSWORD: bWFyX3Bvc3RncmVzcWw=  # Base64-encoded value of 'mar_postgresql'
---
# ConfigMap for PostgreSQL custom configurations (postgresql.conf and pg_hba.conf)
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-2  # Updated ConfigMap name
  namespace: kkm  
  labels:
    app: postgres-2  # Updated label
data:
  postgresql.conf: |
    # Listen on all interfaces
    listen_addresses = '*'
    # Optionally change other settings like max_connections, shared_buffers, etc.

  pg_hba.conf: |
    # Allow all IPs to connect
    host    all             all             0.0.0.0/0            md5
    host    all             all             ::/0                 md5
---
# Persistent Volume definition with generic name
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-2  # Updated volume name
  namespace: kkm  
  labels:
    type: local
    app: postgres-2  # Updated label
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql2  # Updated path to avoid conflict
---
# Persistent Volume Claim definition with generic name
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim-2  # Updated PVC name
  namespace: kkm  
  labels:
    app: postgres-2  # Updated label
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
# Deployment for PostgreSQL (second deployment with unique name)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-2  # Updated deployment name
  namespace: kkm  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-2  # Updated label
  template:
    metadata:
      labels:
        app: postgres-2  # Updated label
    spec:
      imagePullSecrets:
        - name: postgresql-acr-secret  # Image pull secret for Azure Container Registry
      containers:
        - name: postgres
          image: litmus.azurecr.io/postgres:12 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret-2  # Reference to the second secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata-2  # Updated volume name
            - mountPath: /etc/postgresql/postgresql.conf
              name: postgres-config-2  # Updated ConfigMap name
              subPath: postgresql.conf
            - mountPath: /etc/postgresql/pg_hba.conf
              name: postgres-config-2  # Updated ConfigMap name
              subPath: pg_hba.conf
      volumes:
        - name: postgresdata-2
          persistentVolumeClaim:
            claimName: postgres-volume-claim-2  # Updated PVC reference
        - name: postgres-config-2
          configMap:
            name: postgres-config-2  # Updated ConfigMap reference
---
# Service definition for PostgreSQL with internal LoadBalancer for Azure (second instance)
apiVersion: v1
kind: Service
metadata:
  name: postgres-2  # Updated service name
  namespace: kkm  
  labels:
    app: postgres-2  # Updated label
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgres-2  # Updated selector
