---
# ConfigMap for PostgreSQL custom configurations (postgresql.conf and pg_hba.conf)
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgresql  
  labels:
    app: postgres
data:
  postgresql.conf: |
    # Listen on all interfaces
    listen_addresses = '*'

    # Enable pgaudit extension
    shared_preload_libraries = 'pgaudit'

    # pgaudit settings to log all types of activities
    pgaudit.log = 'read, write, ddl, role, login, function'

    # Whether to log system catalog queries
    pgaudit.log_catalog = on

    # Log verbosity for pgaudit
    pgaudit.log_level = info

    # Whether to log the first occurrence of a statement only
    pgaudit.log_statement_once = off

    # Whether to log function parameters
    pgaudit.log_parameter = on

    # Optionally change other settings like max_connections, shared_buffers, etc.
  pg_hba.conf: |
    # Allow all IPs to connect (adjust as needed for your security policy)
    host    all             all             0.0.0.0/0            md5
    host    all             all             ::/0                 md5
---
# ConfigMap for PostgreSQL credentials (username, password, and database)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgresql
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: "ps_db"              
  POSTGRES_USER: YWRtaW4=            
  POSTGRES_PASSWORD: bWFyc19wb3N0Z3Jlc3F1ZWw= 
---
# Persistent Volume definition 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: postgresql  
  labels:
    type: local
    app: postgres
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
# Persistent Volume Claim definition 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: postgresql  
  labels:
    app: postgres
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
# Deployment for PostgreSQL with pgaudit enabled
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgresql  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
        - name: postgresql-acr-secret  # Image pull secret for ACR authentication
      containers:
        - name: postgres
          image: litmus.azurecr.io/postgres:12  # PostgreSQL image from ACR
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
            - mountPath: /etc/postgresql/postgresql.conf
              name: postgres-config
              subPath: postgresql.conf
            - mountPath: /etc/postgresql/pg_hba.conf
              name: postgres-config
              subPath: pg_hba.conf
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
        - name: postgres-config
          configMap:
            name: postgres-config
---
# Service definition for PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgresql  
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgres
