---
# Secret for PostgreSQL credentials (username, password, and database)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgresql
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: cHNfZGI=  # Base64-encoded value of 'ps_db'
  POSTGRES_USER: YWRtaW4=  # Base64-encoded value of 'admin'
  POSTGRES_PASSWORD: bWFyX3Bvc3RncmVzcWw=  # Base64-encoded value of 'mars_postgresql'
---
# ConfigMap for PostgreSQL custom configurations (postgresql.conf and pg_hba.conf)
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgresql  
  labels:
    app: postgres
data:
  postgresql.conf: |
    # Listen on all interfaces
    listen_addresses = '*'
    # Optionally change other settings like max_connections, shared_buffers, etc.

  pg_hba.conf: |
    # Allow all IPs to connect
    host    all             all             0.0.0.0/0            md5
    host    all             all             ::/0                 md5
---
# ClusterRole to grant permissions to manage PersistentVolumes
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # Name of the role
  name: flux-applier-pv-role
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]

---

# ClusterRoleBinding to bind the service account to the ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-applier-pv-role-binding
subjects:
  - kind: ServiceAccount
    name: flux-applier  # This is the service account used by Flux
    namespace: postgresql  # Ensure this matches the namespace of the service account
roleRef:
  kind: ClusterRole
  name: flux-applier-pv-role  # Refers to the ClusterRole we just created
  apiGroup: rbac.authorization.k8s.io
---
# Persistent Volume definition with generic name
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: postgresql  
  labels:
    type: local
    app: postgres
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
---
# Persistent Volume Claim definition with generic name
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  namespace: postgresql  
  labels:
    app: postgres
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Deployment for PostgreSQL (generic name)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgresql  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
        - name: postgresql-acr-secret  # Image pull secret for Azure Container Registry
      containers:
        - name: postgres
          image: litmus.azurecr.io/postgres:12 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret  # Reference to the secret for credentials
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
            - mountPath: /etc/postgresql/postgresql.conf
              name: postgres-config
              subPath: postgresql.conf
            - mountPath: /etc/postgresql/pg_hba.conf
              name: postgres-config
              subPath: pg_hba.conf
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim
        - name: postgres-config
          configMap:
            name: postgres-config
---
# Service definition for PostgreSQL with internal LoadBalancer for Azure
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgresql  
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: postgres
